# Generated by Django 6.0.5 on 2026-05-15 01:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.TextField()),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('platform', models.CharField(blank=True, default='', max_length=128)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=2048)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='pending', max_length=32)),
                ('engine', models.CharField(default='yt-dlp', max_length=32)),
                ('format', models.CharField(blank=True, default='mp4', max_length=16)),
                ('quality', models.CharField(blank=True, default='best', max_length=32)),
                ('media_kind', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('document', 'Document'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=32)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('queue_order', models.IntegerField(default=0)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the download finished (used for retention).', null=True)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('http_connections', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DownloadJobMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_downloaded', models.BigIntegerField(default=0)),
                ('bytes_total', models.BigIntegerField(default=0)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('avg_speed_bps', models.FloatField(blank=True, null=True)),
                ('peak_speed_bps', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('last_speed_str', models.CharField(blank=True, default='', max_length=64)),
                ('last_eta_str', models.CharField(blank=True, default='', max_length=64)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('partial_rel_path', models.CharField(blank=True, default='', max_length=1024)),
                ('resume_etag', models.CharField(blank=True, default='', max_length=255)),
                ('resume_last_modified', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='downloader.downloadjob')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.TextField()),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('platform', models.CharField(blank=True, default='', max_length=128)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='downloadjob',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='downloader.playlist'),
        ),
        migrations.CreateModel(
            name='DownloadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1024)),
                ('file_name', models.CharField(blank=True, default='', max_length=512)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('storage_backend', models.CharField(default='local', max_length=16)),
                ('is_deleted', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_files', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='downloader.downloadjob')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_deleted', '-created_at'], name='downloader__user_id_3d5801_idx'), models.Index(fields=['job'], name='downloader__job_id_9aebdc_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('started', 'Started'), ('progress', 'Progress'), ('retried', 'Retried'), ('done', 'Done'), ('error', 'Error'), ('cancelled', 'Cancelled')], max_length=32)),
                ('message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('worker_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='downloader.downloadjob')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['job', 'created_at'], name='downloader__job_id_5676ea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['user', 'status', '-created_at'], name='downloader__user_id_516a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['user', 'queue_order'], name='downloader__user_id_4ed1fd_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['user', 'playlist'], name='downloader__user_id_1e1e88_idx'),
        ),
    ]
