# Generated by Django 6.0.5 on 2026-05-15 00:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('platform', models.CharField(blank=True, default='generic', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='pending', max_length=32)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('speed', models.CharField(blank=True, default='', max_length=64)),
                ('eta', models.CharField(blank=True, default='', max_length=64)),
                ('file_path', models.CharField(blank=True, default='', max_length=1024)),
                ('file_size', models.BigIntegerField(default=0)),
                ('format', models.CharField(blank=True, default='mp4', max_length=16)),
                ('quality', models.CharField(blank=True, default='best', max_length=32)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_to_telegram', models.BooleanField(default=False)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='downloader.downloadjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
