# Generated by Django 6.0.5 on 2026-05-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadjob',
            name='upload_to_google_drive',
            field=models.BooleanField(default=False),
        ),
    ]
