# Generated by Django 6.0.5 on 2026-05-15 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token_encrypted', models.TextField(blank=True, default='')),
                ('chat_id', models.CharField(blank=True, default='', max_length=128)),
                ('auto_send', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
