# Generated by Django 6.0.5 on 2026-05-15 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('downloader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('auto_send', models.BooleanField(default=False)),
                ('bot_token_encrypted', models.TextField(blank=True, default='')),
                ('chat_id', models.CharField(blank=True, default='', max_length=128)),
                ('chat_username', models.CharField(blank=True, default='', max_length=128)),
                ('chat_type', models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('channel', 'Channel')], default='private', max_length=16)),
                ('max_file_size_mb', models.PositiveIntegerField(default=50)),
                ('use_local_bot_api', models.BooleanField(default=False)),
                ('local_bot_api_url', models.URLField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('telegram_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('telegram_file_id', models.CharField(blank=True, default='', max_length=256)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='integrations.telegramconfig')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_sends', to='downloader.downloadedfile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_sends', to='downloader.downloadjob')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['job', 'status'], name='integration_job_id_7f9653_idx'), models.Index(fields=['config', 'status'], name='integration_config__1acc6e_idx')],
            },
        ),
    ]
