# Generated by Django 6.0.5 on 2026-05-15 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('downloader', '0002_downloadjob_upload_to_google_drive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrabberCrawlTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('crawling', 'Crawling'), ('done', 'Done'), ('error', 'Error'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('content_size', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('crawled_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='grabber.grabbercrawltask')),
            ],
            options={
                'ordering': ('depth', '-discovered_at'),
            },
        ),
        migrations.CreateModel(
            name='GrabberProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_url', models.URLField(max_length=2048)),
                ('max_depth', models.PositiveSmallIntegerField(default=3, help_text='Maximum crawl depth. 0 = current page only.')),
                ('max_pages', models.PositiveIntegerField(default=500, help_text='Maximum pages to crawl per project run.')),
                ('max_files', models.PositiveIntegerField(default=2000, help_text='Maximum files to discover per project run.')),
                ('respect_robots_txt', models.BooleanField(default=True)),
                ('user_agent', models.CharField(blank=True, default='AIO-Grabber/1.0', max_length=512)),
                ('crawl_delay', models.FloatField(default=1.0, help_text='Seconds between successive requests to the same domain.')),
                ('concurrency', models.PositiveSmallIntegerField(default=3, help_text='Max concurrent crawl requests.')),
                ('use_javascript', models.BooleanField(default=False, help_text='Use Playwright for JavaScript-rendered pages.')),
                ('auth_json', models.JSONField(blank=True, default=dict, help_text='Stored as {"type": "cookie|form", "cookies": {...}, "login_url": "...", "username": "...", "password_encrypted": "..."}')),
                ('schedule_cron', models.CharField(blank=True, default='', help_text="Optional cron expression for scheduled re-crawls (e.g. '0 2 * * *' for 2 AM daily).", max_length=128)),
                ('rewrite_links', models.BooleanField(default=False, help_text='Rewrite HTML href/src for offline browsing.')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('crawling', 'Crawling'), ('paused', 'Paused'), ('done', 'Done'), ('error', 'Error')], default='idle', max_length=16)),
                ('pages_crawled', models.PositiveIntegerField(default=0)),
                ('files_discovered', models.PositiveIntegerField(default=0)),
                ('files_downloaded', models.PositiveIntegerField(default=0)),
                ('bytes_downloaded', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('celery_beat_task_name', models.CharField(blank=True, default='', help_text='Name of the periodic task for scheduled re-crawl (if schedule_cron is set).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grabber_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GrabberFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('include', 'Include'), ('exclude', 'Exclude')], max_length=10)),
                ('target', models.CharField(choices=[('url', 'URL Pattern'), ('file_type', 'File Extension'), ('file_size', 'File Size Range'), ('domain', 'Domain'), ('keyword', 'Keyword in URL/Title')], max_length=16)),
                ('pattern', models.CharField(help_text='Glob pattern (e.g. *.mp4, *.pdf) or regex if is_regex=True.', max_length=512)),
                ('is_regex', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='grabber.grabberproject')),
            ],
            options={
                'ordering': ('filter_type', 'target'),
            },
        ),
        migrations.CreateModel(
            name='GrabberDiscoveredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=2048)),
                ('file_name', models.CharField(blank=True, default='', max_length=1024)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=16)),
                ('extension', models.CharField(blank=True, default='', max_length=32)),
                ('page_url', models.URLField(blank=True, default='', help_text='The page URL where this file was discovered.', max_length=2048)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('queued', 'Queued (Awaiting Download)'), ('downloaded', 'Downloaded'), ('skipped', 'Skipped'), ('error', 'Error')], default='discovered', max_length=16)),
                ('checksum', models.CharField(blank=True, default='', help_text='SHA256 of file content (set after download).', max_length=64)),
                ('is_duplicate', models.BooleanField(default=False, help_text='Flag indicating duplicate detection has been run.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crawl_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discovered_files', to='grabber.grabbercrawltask')),
                ('download_job', models.ForeignKey(blank=True, help_text='The DownloadJob created when the user decides to download this file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grabber_files', to='downloader.downloadjob')),
                ('duplicate_of', models.ForeignKey(blank=True, help_text='If set, this file is a duplicate of another (same SHA256).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='grabber.grabberdiscoveredfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_files', to='grabber.grabberproject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='grabbercrawltask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_tasks', to='grabber.grabberproject'),
        ),
        migrations.AddIndex(
            model_name='grabberproject',
            index=models.Index(fields=['user', 'status'], name='grabber_gra_user_id_d977e2_idx'),
        ),
        migrations.AddIndex(
            model_name='grabberproject',
            index=models.Index(fields=['user', '-created_at'], name='grabber_gra_user_id_3d5d04_idx'),
        ),
        migrations.AddIndex(
            model_name='grabberdiscoveredfile',
            index=models.Index(fields=['project', 'file_type'], name='grabber_gra_project_ee1c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='grabberdiscoveredfile',
            index=models.Index(fields=['project', 'status'], name='grabber_gra_project_62b2af_idx'),
        ),
        migrations.AddIndex(
            model_name='grabberdiscoveredfile',
            index=models.Index(fields=['file_url'], name='grabber_file_url_idx'),
        ),
        migrations.AddIndex(
            model_name='grabbercrawltask',
            index=models.Index(fields=['project', 'depth'], name='grabber_gra_project_aba0fb_idx'),
        ),
        migrations.AddIndex(
            model_name='grabbercrawltask',
            index=models.Index(fields=['project', 'status'], name='grabber_gra_project_7b6bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='grabbercrawltask',
            index=models.Index(fields=['url'], name='grabber_crawl_url_idx'),
        ),
    ]
