# Generated by Django 6.0.5 on 2026-05-15 04:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabber', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('site_url', models.URLField(max_length=2048)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password_encrypted', models.TextField(blank=True, default='')),
                ('cookies', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('login_url', models.URLField(blank=True, default='', max_length=2048)),
                ('login_method', models.CharField(choices=[('form', 'Form POST'), ('cookie', 'Cookie Injection'), ('header', 'Header Auth'), ('basic', 'Basic Auth')], default='cookie', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Account',
                'verbose_name_plural': 'Site Accounts',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_active'], name='grabber_sit_user_id_e17351_idx'), models.Index(fields=['user', '-created_at'], name='grabber_sit_user_id_14c2c3_idx')],
            },
        ),
    ]
