# Generated by Django 6.0.5 on 2026-05-16 10:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grabber", "0002_siteaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="grabberproject",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
