# Generated by Django 6.0.5 on 2026-05-16 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grabber", "0003_grabberproject_error_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrabberLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("debug", "Debug"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("url", models.URLField(blank=True, default="", max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="grabber.grabberproject",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["project", "level"],
                        name="grabber_grab_project_e7c17f_idx",
                    ),
                    models.Index(
                        fields=["project", "-created_at"],
                        name="grabber_grab_project_1f98e8_idx",
                    ),
                ],
            },
        ),
    ]
